console.log(1 === 1);
console.log(1 === "1");
console.log(3 < 2);
console.log(2 > 0);
console.log(7 >= 7);
console.log(6 <= 5);
console.log(3 !== 3);
console.log("hola" !== "hola");
console.log(4 !== "4");
console.log(false === true);
console.log(true);
console.log(false);
